version: '3'

services:
  postgres_dev:
     container_name: 'postgres_dev'
     image: postgres
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
     ports:
       - "5432:5432"
  postgres_test:
    container_name: 'postgres_test'
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"   
  postgres_prod:
    container_name: 'postgres_prod'
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"   
  dbGUI:
    container_name: 'pgadmin'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres_dev
      - postgres_test
      - postgres_prod
